import type { SystemCategory } from "@/db/schema/categories";

export const CATEGORY_DEFAULT_ABV = new Map<SystemCategory, number>([
	["absinthe", 0.65],
	["amaro", 0.3],
	["aperitif", 0.2],
	["aquavit", 0.4],
	["armagnac", 0.4],
	["baijiu", 0.52],
	["beer", 0.05],
	["bitters", 0.4],
	["bourbon", 0.4],
	["brandy", 0.4],
	["cachaca", 0.4],
	["calvados", 0.4],
	["champagne", 0.12],
	["cocktail_bitters", 0.45],
	["cognac", 0.4],
	["gin", 0.4],
	["grappa", 0.4],
	["herbal_liqueur", 0.4],
	["liqueur", 0.25],
	["mezcal", 0.4],
	["pisco", 0.4],
	["port", 0.2],
	["rum", 0.4],
	["rye", 0.4],
	["sake", 0.15],
	["sherry", 0.17],
	["shochu", 0.25],
	["tequila", 0.4],
	["vermouth", 0.18],
	["vodka", 0.4],
	["whiskey", 0.4],
	["wine", 0.12],
]);

/**
 * Note that deburr is expected to first handle accented characters, so we don't to
 * consider f.e. cachaca -> cachaça here.
 */
export const CATEGORY_ALIASES = new Map<SystemCategory, string[]>([
	["gin", ["gin"]],
	["genever", ["genever", "jenever"]],
	["vodka", ["vodka", "wodka"]],
	["whiskey", ["whiskey", "whisky"]],
	["bourbon", ["bourbon", "bourbon whiskey", "bourbon whisky"]],
	["rye", ["rye", "rye whiskey", "rye whisky"]],
	["rum", ["rum", "rhum", "rom", "ron"]],
	["tequila", ["tequila"]],
	["mezcal", ["mezcal"]],
	["brandy", ["brandy"]],
	["cognac", ["cognac"]],
	["armagnac", ["armagnac"]],
	["calvados", ["calvados", "apple brandy"]],
	["grappa", ["grappa"]],
	["pisco", ["pisco"]],
	["cachaca", ["cachaca"]],
	["baijiu", ["baijiu"]],
	["shochu", ["shochu", "soju"]],
	["absinthe", ["absinthe", "absinth"]],
	["aquavit", ["aquavit", "akvavit", "akevitt"]],
	[
		"vermouth",
		[
			"vermouth",
			"sweet vermouth",
			"dry vermouth",
			"blanc vermouth",
			"bianco vermouth",
			"fortified wine",
		],
	],
	[
		"sherry",
		["sherry", "fino", "amontillado", "oloroso", "pedro ximenez", "px"],
	],
	["port", ["port", "tawny port", "ruby port", "vintage port"]],
	["aperitif", ["aperitif", "aperitivo"]],
	["sake", ["sake", "rice wine"]],
	["amaro", ["amaro", "amari", "italian bitter"]],
	["bitters", ["bitters", "bitter", "aromatic bitters"]],
	[
		"liqueur",
		[
			"liqueur",
			"liquer",
			"cordial",
			"cointreau",
			"triple sec",
			"grand marnier",
			"amaretto",
		],
	],
	["herbal_liqueur", ["herbal liqueur", "herbal", "digestif"]],
	["wine", ["wine", "red wine", "white wine", "rose wine"]],
	["champagne", ["champagne", "sparkling wine", "prosecco", "cava", "cremant"]],
	[
		"beer",
		["beer", "ale", "lager", "stout", "porter", "ipa", "bier", "pilsner"],
	],
	[
		"citrus",
		[
			"lemon",
			"lemon juice",
			"lime",
			"lime juice",
			"orange",
			"orange juice",
			"grapefruit",
			"grapefruit juice",
			"citrus",
			"bergamot",
			"yuzu",
		],
	],
	[
		"cocktail_bitters",
		[
			"angostura",
			"peychaud",
			"orange bitters",
			"walnut bitters",
			"chocolate bitters",
		],
	],
	["egg", ["egg", "egg white", "egg yolk", "whole egg", "eggs"]],
	[
		"syrup",
		["simple", "simple syrup", "grenadine", "orgeat", "demerara", "gomme"],
	],
	["dairy", ["cream", "milk", "heavy cream", "half and half", "butter"]],

	["soda", []],
	["juice", []],
	["herb", []],
	["fruit", []],
	["honey", []],
	["garnish", []],
	["other", []],
]);
