import type { SystemCategory } from "@/db/schema/categories";

export const CATEGORY_DEFAULT_ABV = new Map<SystemCategory, number>([
	["absinthe", 65],
	["amaro", 30],
	["aperitif", 20],
	["aquavit", 40],
	["armagnac", 40],
	["baijiu", 52],
	["beer", 5],
	["bitters", 40],
	["bourbon", 40],
	["brandy", 40],
	["cachaca", 40],
	["calvados", 40],
	["champagne", 12],
	["cocktail_bitters", 45],
	["cognac", 40],
	["gin", 40],
	["grappa", 40],
	["herbal_liqueur", 40],
	["liqueur", 25],
	["mezcal", 40],
	["pisco", 40],
	["port", 20],
	["rum", 40],
	["rye", 40],
	["sake", 15],
	["sherry", 17],
	["shochu", 25],
	["tequila", 40],
	["vermouth", 18],
	["vodka", 40],
	["whiskey", 40],
	["wine", 12],
]);
