import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { getIconData } from "@iconify/utils";
import lucide from "@iconify-json/lucide/icons.json" with { type: "json" };
import { ICONS } from "./config.ts";

const start = performance.now();
const here = join(fileURLToPath(import.meta.url), "..");
const kits = { lucide };

function loadLocal(name: string) {
	const svg = readFileSync(join(here, "svgs", `${name}.svg`), "utf8");
	const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
	if (!viewBox) throw new Error(`No viewBox in svgs/${name}.svg`);
	const body = svg
		.replace(/^[\s\S]*?<svg[^>]*>/, "")
		.replace(/<\/svg>\s*$/, "")
		.trim();
	return { viewBox, body };
}

function loadFromKit(kit: keyof typeof kits, name: string) {
	const data = getIconData(kits[kit], name);
	if (!data) throw new Error(`Icon "${name}" not found in kit "${kit}"`);
	return { viewBox: `0 0 ${data.width} ${data.height}`, body: data.body };
}

const localNames = Object.keys(ICONS).sort();

const symbols = localNames
	.map((name) => {
		const source = ICONS[name as keyof typeof ICONS];
		const { viewBox, body } =
			"local" in source
				? loadLocal(name)
				: loadFromKit(source.kit, source.name);
		return `<symbol id="${name}" viewBox="${viewBox}">${body}</symbol>`;
	})
	.join("\n");

const header = "// Generated by src/libs/icons/build.ts. Do not edit.";
const toUnion = (xs: string[]) => xs.map((n) => `\t| "${n}"`).join("\n");
const pascal = (s: string) =>
	s
		.split("-")
		.map((p) => p[0].toUpperCase() + p.slice(1))
		.join("");

const kitTypeExports = Object.entries(kits)
	.map(([kit, set]) => {
		const names = [
			...Object.keys(set.icons),
			...Object.keys(set.aliases ?? {}),
		].sort();
		return `export type ${pascal(kit)}IconName =\n${toUnion(names)};`;
	})
	.join("\n\n");

writeFileSync(
	join(here, "sprite.svg"),
	`<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1" style="display: none;">\n${symbols}\n</svg>\n`,
);
writeFileSync(
	join(here, "types.ts"),
	`${header}\nexport type IconName =\n${toUnion(localNames)};\n`,
);
writeFileSync(join(here, "kits.types.ts"), `${header}\n${kitTypeExports}\n`);

console.log(
	`Built ${localNames.length} icons in ${Math.round(performance.now() - start)}ms → src/libs/icons/{sprite.svg,types.ts,kits.types.ts}`,
);
