/**
 * Source of truth for the icon sprite. Edit this file to add, rename, or
 * swap icons; then run `npm run icons:build` to regenerate `icons.svg` and
 * `types.ts`.
 *
 * https://icon-sets.iconify.design/lucide/
 */
import type { LucideIconName } from "./kits.types";

type IconSource = { kit: "lucide"; name: LucideIconName } | { local: true };

export const ICONS = {
	"angle-down": { kit: "lucide", name: "chevron-down" },
	"angle-left": { kit: "lucide", name: "chevron-left" },
	"angle-right": { kit: "lucide", name: "chevron-right" },
	"angle-up": { kit: "lucide", name: "chevron-up" },
	"angles-right": { kit: "lucide", name: "chevrons-right" },
	"arrow-down": { kit: "lucide", name: "arrow-down" },
	"arrow-down-from-line": { kit: "lucide", name: "arrow-down-from-line" },
	"arrow-down-to-arc": { local: true },
	"arrow-down-to-dotted-line": { local: true },
	"arrow-left": { kit: "lucide", name: "arrow-left" },
	"arrow-right": { kit: "lucide", name: "arrow-right" },
	"arrow-rotate-left": { kit: "lucide", name: "rotate-ccw" },
	"circle-check": { kit: "lucide", name: "circle-check" },
	"circle-exclamation": { kit: "lucide", name: "circle-alert" },
	"circle-info": { kit: "lucide", name: "info" },
	"circle-small": { kit: "lucide", name: "circle-small" },
	"circle-xmark": { kit: "lucide", name: "circle-x" },
	"duotone-image": { local: true },
	"duotone-input-text": { local: true },
	"duotone-martini-glass": { local: true },
	"duotone-memo-pad": { local: true },
	"duotone-shop": { local: true },
	"duotone-table-tree": { local: true },
	"duotone-wine-bottle": { local: true },
	"external-link": { kit: "lucide", name: "external-link" },
	"glass-citrus": { local: true },
	"heart-solid": { local: true },
	"id-card": { kit: "lucide", name: "id-card" },
	"magnifying-glass": { kit: "lucide", name: "search" },
	"martini-glass": { kit: "lucide", name: "martini" },
	"memo-pad": { kit: "lucide", name: "notebook" },
	"pen-to-square": { kit: "lucide", name: "square-pen" },
	"sliders-horizontal": { kit: "lucide", name: "sliders-horizontal" },
	"sort-down": { kit: "lucide", name: "sort-desc" },
	"sort-up": { kit: "lucide", name: "sort-asc" },
	"star-off": { kit: "lucide", name: "star-off" },
	"sun-bright": { kit: "lucide", name: "sun" },
	"table-list": { kit: "lucide", name: "table" },
	"triangle-exclamation": { kit: "lucide", name: "triangle-alert" },
	"wine-glass": { kit: "lucide", name: "wine" },
	bars: { kit: "lucide", name: "menu" },
	building: { kit: "lucide", name: "building" },
	camera: { kit: "lucide", name: "camera" },
	check: { kit: "lucide", name: "check" },
	clone: { local: true },
	copy: { kit: "lucide", name: "copy" },
	display: { kit: "lucide", name: "monitor" },
	ellipsis: { kit: "lucide", name: "ellipsis" },
	expand: { kit: "lucide", name: "expand" },
	filter: { kit: "lucide", name: "filter" },
	gear: { kit: "lucide", name: "settings" },
	globe: { kit: "lucide", name: "globe" },
	heart: { local: true },
	image: { kit: "lucide", name: "image" },
	memo: { kit: "lucide", name: "file-text" },
	minus: { kit: "lucide", name: "minus" },
	moon: { kit: "lucide", name: "moon" },
	pen: { kit: "lucide", name: "pen" },
	plus: { kit: "lucide", name: "plus" },
	redo: { kit: "lucide", name: "redo-2" },
	repeat: { kit: "lucide", name: "repeat-2" },
	share: { kit: "lucide", name: "share" },
	sort: { kit: "lucide", name: "arrow-down-up" },
	sparkles: { kit: "lucide", name: "sparkles" },
	star: { kit: "lucide", name: "star" },
	tag: { kit: "lucide", name: "tag" },
	tags: { kit: "lucide", name: "tags" },
	trash: { kit: "lucide", name: "trash-2" },
	trophy: { kit: "lucide", name: "trophy" },
	undo: { kit: "lucide", name: "undo-2" },
	users: { kit: "lucide", name: "users" },
	xmark: { kit: "lucide", name: "x" },
} as const satisfies Record<string, IconSource>;
